apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: main-db
          image: DB_IMAGE
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: DB_PASSWORD
          - name: POSTGRES_USER
            value: DB_USER
          - name: POSTGRES_DB
            value: DB_NAME
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
